backend:
    name: git-gateway
    repo: Sibasish19/my-blog
    branch: master
    identity_url: 'https://amazing-noether-7fb791.netlify.app/.netlify/identity'
    gateway_url: 'https://amazing-noether-7fb791.netlify.app/.netlify/git'
    site_domain: 'https://amazing-noether-7fb791.netlify.app/'
    squash_merges: true
    accept_roles:
        - admin
        - editor

display_url: https://amazing-noether-7fb791.netlify.app
# logo_url:

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
    - name: 'blogs'
      label: 'Blogs'
      folder: 'content/blogs'
      create: true
      media_folder: ''
      public_folder: ''
      path: '{{title}}/index'
      fields:
          - {
                label: 'Layout',
                name: 'layout',
                widget: 'hidden',
                default: 'blogs',
            }
          - {
                name: 'title',
                label: 'Title',
                widget: 'string',
                pattern:
                    [
                        '.{10,40}',
                        'Must have at least 10 and at max 40 characters',
                    ],
            }
          - { name: 'publishedDate', label: Published date, widget: 'datetime' }
          - {
                name: 'author',
                label: 'Author',
                widget: 'string',
                default: 'Siabsish Mohanty',
            }
          - { name: 'banner', label: 'Cover image', widget: 'image' }
          - {
                name: 'bannerCredit',
                label: 'Image Credit',
                widget: 'markdown',
                required: false,
            }
          - {
                name: 'category',
                label: 'Select a category',
                widget: 'select',
                options:
                    [
                        'Technology',
                        'Observation',
                        'Motivation',
                        'Story',
                        'Politics',
                        'Cartoon',
                    ],
            }
          - {
                name: 'summary',
                label: 'Summary',
                widget: 'text',
                pattern:
                    [
                        '.{100,250}',
                        'Must have at least 100 and at max 250 characters',
                    ],
            }
          - { name: 'keywords', label: 'Tags', widget: 'list' }
          - {
                name: 'body',
                label: 'Content',
                widget: 'markdown',
                pattern:
                    [
                        '.[\S\s]{1000,4000}',
                        'Must have at least 1000 and at max 4000 characters',
                    ],
            }
